import type { Metadata } from "next";
import {  Inter } from "next/font/google";
import "./globals.css";
import Layout from "../components/Layout";

const inter = Inter({subsets:['latin']});

export const metadata: Metadata = {
title:'Website Pribadi',
description:'Website pribadi untuk menampilkan proyek dan esai.',
}
// // eslint-disable-next-line @typescript-eslint/no-unused-vars
// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });
// // eslint-disable-next-line @typescript-eslint/no-unused-vars
// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });


// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}><Layout>{children}</Layout>
      </body>
    </html>
  );

}
